name: which_film
version: 0.9.0
dependencies:
  http:
  logging:
  angular2:
  browser:
  dart_to_js_script_rewriter:
  usage:
dev_dependencies:
  grinder:
  test:
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
